/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//New form for Conference Expense reimbursement

package project1;
import java.awt.*;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author Aditi
 */
public class NewFormStudent extends javax.swing.JFrame {

    /**
     * Creates new form NewFormStudent
     */
    public NewFormStudent() {
        initComponents();
    }
    String username;
     Statement stmt2=null,stmt1=null;
        ResultSet r2 = null,r3=null;
        Connection c1;
        public String sendto = null ;  
    
    public void setVal(Connection c,String s) 
    {
     username = s;
    c1= c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jDialog3 = new javax.swing.JDialog();
        jSeparator1 = new javax.swing.JSeparator();
        FormA1 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        FormA2 = new javax.swing.JButton();
        FormA3 = new javax.swing.JButton();
        FormA4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        frame2 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        name_of_conference = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        date_of_conference = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        city_of_conference = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        country_of_conference = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        cost_travel = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Normal = new java.awt.Checkbox();
        Urgent = new java.awt.Checkbox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel4.setText("jLabel4");

        jFormattedTextField1.setText("jFormattedTextField1");

        jTextField2.setText("jTextField2");

        jTextField6.setText("jTextField6");

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(715, 800));

        FormA1.setText("Form A1");
        FormA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FormA1MouseClicked(evt);
            }
        });
        FormA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormA1ActionPerformed(evt);
            }
        });
        jInternalFrame1.setVisible(true);

        jInternalFrame1.setVisible(false);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        FormA2.setText("Form A2");
        FormA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FormA2MouseClicked(evt);
            }
        });

        FormA3.setText("Form A3");

        FormA4.setText("Form A4");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 255));
        jLabel1.setText("Create  your own Forms");

        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Submit");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        frame2.setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        frame2.setVisible(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Form A1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Reimbursement of Conference Expenses");

        jLabel5.setText("Date of Application");

        jLabel6.setText("Addressed To: ");

        jLabel7.setText("Subject :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel8.setText("Supervisor :");

        name_of_conference.setText("Name of Conference :");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        date_of_conference.setText("Date of Conference : ");

        city_of_conference.setText("City of Conference :");

        country_of_conference.setText("Country of Conference:");

        jLabel9.setText("Registration Fees :");

        cost_travel.setText("Travel Cost :");

        jLabel10.setText("Level of Urgency :");

        Normal.setLabel("checkbox1");

        Urgent.setLabel("checkbox2");

        jLabel11.setText("Normal");

        jLabel12.setText("Very Urgent");

        jLabel14.setText("Please enter date as yyyy/mm/dd");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HOD, CSE", "HOD, ECE", "HOD,CCE" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frame2Layout = new javax.swing.GroupLayout(frame2.getContentPane());
        frame2.getContentPane().setLayout(frame2Layout);
        frame2Layout.setHorizontalGroup(
            frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frame2Layout.createSequentialGroup()
                        .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(41, 41, 41))
                                .addGroup(frame2Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(59, 59, 59)))
                            .addGroup(frame2Layout.createSequentialGroup()
                                .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(name_of_conference)
                                    .addComponent(date_of_conference)
                                    .addComponent(city_of_conference))
                                .addGap(26, 26, 26)))
                        .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                            .addGroup(frame2Layout.createSequentialGroup()
                                .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 132, Short.MAX_VALUE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(frame2Layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel13))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(frame2Layout.createSequentialGroup()
                        .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(country_of_conference)
                            .addComponent(jLabel9)
                            .addComponent(cost_travel)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField7)
                                .addComponent(jTextField8)
                                .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                            .addGroup(frame2Layout.createSequentialGroup()
                                .addComponent(Normal, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(37, 37, 37)
                                .addComponent(Urgent, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frame2Layout.setVerticalGroup(
            frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame2Layout.createSequentialGroup()
                        .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name_of_conference)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(date_of_conference)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(city_of_conference)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(country_of_conference)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cost_travel)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(Normal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Urgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(frame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FormA1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FormA2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FormA3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FormA4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(25, 25, 25))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(frame2, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(FormA1)
                                .addGap(18, 18, 18)
                                .addComponent(FormA2)
                                .addGap(18, 18, 18)
                                .addComponent(FormA3)
                                .addGap(18, 18, 18)
                                .addComponent(FormA4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(26, 26, 26)
                        .addComponent(jButton2)
                        .addGap(142, 142, 142))))
        );

        pack();
    }// </editor-fold>                        

    private void FormA1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        System.out.println("You clicked a button");
        //jInternalFrame1.getContentPane().add(FormA1);
        //jInternalFrame1.pack();
        jInternalFrame1.setVisible(true);
        
    }                                      

    private void FormA1MouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        frame2.setVisible(true);
    }                                   

    private void FormA2MouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        frame2.setVisible(false);
        //jDialog1.setVisible(true);
        
    }                                   

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here
       // jDialog1.setVisible(true);
       // setLocationRelativeTo(frame2);
       // setTitle("Your form has been successfully submitted!");
        
        
    }                                        

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Your form has been submitted successfully!");
       try {
        System.out.println("Button Clicked!!!");
       
            //c1 = new connection();
            stmt2 = c1.createStatement();
            String q1 = "use process";
            r2 = stmt2.executeQuery(q1);
            String h = "@q1 + hellooooooo";
            System.out.println(h);
            stmt1 = c1.createStatement();
            String owner_id= username;
            
           // String q = "Insert into form_a1 values("'"+date_appl+"'","'"+subject+"'");
           
            //ResultSet r1 = stmt1.executeQuery("INSERT INTO form_a1(date_appl, subject, supervisor, name_of_conf, date_of_conf, city_of_conf, country_of_conf, reg_fee, travel_cost )" + " VALUES(@date_appl, @subject, @supervisor, @name_of_conf, @date_of_conf, @city_of_conf, @country_of_conf, @reg_fee, @travel_cost);");
       // System.out.println("Data Inserted");
          
        String date = jTextField10.getText();
        String subject = jTextArea1.getText();
        String supervisor = jTextField3.getText();
        String name_of_conf = jTextField1.getText();
        String date_of_conf = jTextField4.getText();
        String city_of_conf = jTextField5.getText();
        String country_of_conf = jTextField7.getText();
        String aa = jTextField8.getText();
        int reg_fee = Integer.parseInt(aa);
        Statement sss0= c1.createStatement();
        int travel_cost = Integer.parseInt(jTextField9.getText());
        String ss0 = "Select form_id from form_a1 order by form_id DESC LIMIT 1";
        ResultSet rs3 = sss0.executeQuery(ss0);
        System.out.println("heyaaaaaaaaaaaaa");
        rs3.last();
        int a1 = rs3.getInt("form_id")+1;
        System.out.println(a1);
        String ss = "INSERT INTO form_a1 (form_id,owner_id,date_appl, subject, supervisor, name_of_conf, date_of_conf, city_of_conf, country_of_conf, reg_fee, travel_cost ) VALUES ('"+a1+"','"+owner_id+"','"+date+"','"+subject+"','"+supervisor+"','"+name_of_conf+"','"+date_of_conf+"','"+city_of_conf+"','"+country_of_conf+"',"+reg_fee+","+travel_cost+");";
        System.out.println(ss);
       try{
           String sendto1 =  (String) jComboBox1.getSelectedItem().toString();
           System.out.println(sendto1);
            if(sendto1 == null)
                sendto1 = "HOD, CSE";
            
            String se = "SELECT user_id from user where user_des = '"+sendto1+"';";
            System.out.println(se);
            Statement s = c1.createStatement();
            rs3 = s.executeQuery(se);
            rs3.last();
            sendto = rs3.getString("user_id");
            //System.out.println("SENDInG To"+sendto);
            } catch (SQLException ex) {
            Logger.getLogger(NewFormStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        String ss1 = "INSERT INTO access_a1 VALUES ('"+a1+"','"+sendto+"');";
        String ss2 = "INSERT INTO access_a1 VALUES ('"+a1+"','"+owner_id+"');";

        sss0.executeUpdate(ss1) ;
        sss0.executeUpdate(ss2) ;
        
        stmt1.executeUpdate(ss);
           
        } catch (SQLException ex) {
            Logger.getLogger(NewFormStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
         
            
        /*     
            while(r1.next())
            {
                
                   //  System.out.println(subject);
               
               String user = r1.getString("user_id");
                String date_appl = r1.getString("date_appl");
                String subject = r1.getString("subject");
                String supervisor = r1.getString("supervisor");
                String name_of_conf = r1.getString("name_of_conf");
                String date_of_conf = r1.getString("date_of_conf");
                String city_of_conf = r1.getString("city_of_conf");
                String country_of_conf = r1.getString("country_of_conf");
                String reg_fee = r1.getString("reg_fee");
                String travel_cost = r1.getString("travel_cost");
               // String logging_cost = r1.getString("logging_cost");
                //String level_urgency = r1.getString("level_of_urgency");
   
                //setting the values back to the fields!
               /* date_appl.setString(""+date_appl);
                 subject.setString("subject");
                 supervisor = r1.getString("supervisor");
                name_of_conf = r1.getString("name_of_conf");
                 date_of_conf = r1.getString("date_of_conf");
                 city_of_conf = r1.getString("city_of_conf");
                 country_of_conf = r1.getString("country_of_conf");
                 reg_fee = r1.getString("reg_fee");
                 travel_cost = r1.getString("travel_cost");
                 logging_cost = r1.getString("logging_cost");
                 level_urgency = r1.getString("level_of_urgency");*/
                
            //stmt1.close();
        
    }                                     

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {                                      
//cancel button deletes the row from the table
        frame2.setVisible(false);
        JOptionPane.showMessageDialog(this, "Your form has not been sent.");
        
        Statement stmt3=null,stmt4=null;
ResultSet r2;
        try {
         stmt3 = c1.createStatement();
            String q3 = "use form_a1";
             r2 = stmt3.executeQuery(q3);
             
       //  stmt4 = c1.createStatement();
        
             
        }
        catch (SQLException e)
        {
            System.out.println(e);
        }
        
        // TODO add your handling code here:
    }                                     

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
            // TODO add your handling code here:
            
            
        
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewFormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewFormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewFormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewFormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewFormStudent().setVisible(true);
            }
        });
        
        JDialog jDialog1 = new JDialog();
//Popula te the box
        jDialog1.setSize(400,400);
        jDialog1.setVisible(false);
        
 
        JFrame frame = new JFrame("JFrame Source Demo");
        frame.setVisible(true);
		// Add a window listner for close button
		frame.addWindowListener(new WindowAdapter() {

			public void windowClosing(WindowEvent e) {
				System.exit(0);
			}
		});
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton FormA1;
    private javax.swing.JButton FormA2;
    private javax.swing.JButton FormA3;
    private javax.swing.JButton FormA4;
    private java.awt.Checkbox Normal;
    private java.awt.Checkbox Urgent;
    private javax.swing.JLabel city_of_conference;
    private javax.swing.JLabel cost_travel;
    private javax.swing.JLabel country_of_conference;
    private javax.swing.JLabel date_of_conference;
    private javax.swing.JInternalFrame frame2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel name_of_conference;
    // End of variables declaration                   
}
